"""Carts, orders, the order state machine, stock reservations and payments."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    CHAR,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ..extensions import db
from .catalog import Product
from .enums import AddressType, OrderStatus, PaymentEventKind, PaymentStatus, ReservationStatus, pg_enum
from .mixins import TimestampMixin

ORDER_STATUS = pg_enum(OrderStatus, "order_status")


class Cart(TimestampMixin, db.Model):
    """Server-side cart owned by a user or, before login, by an opaque guest token."""

    __tablename__ = "carts"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), unique=True)
    guest_token: Mapped[uuid.UUID | None] = mapped_column(Uuid, unique=True)

    items: Mapped[list[CartItem]] = relationship(
        back_populates="cart", cascade="all, delete-orphan", passive_deletes=True
    )

    __table_args__ = (CheckConstraint("num_nonnulls(user_id, guest_token) = 1", name="exactly_one_owner"),)


class CartItem(TimestampMixin, db.Model):
    """One product line in a cart, active or saved for later."""

    __tablename__ = "cart_items"

    id: Mapped[int] = mapped_column(primary_key=True)
    cart_id: Mapped[int] = mapped_column(ForeignKey("carts.id", ondelete="CASCADE"), nullable=False)
    product_id: Mapped[int] = mapped_column(ForeignKey("products.id", ondelete="CASCADE"), nullable=False)
    quantity: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    # Kept in the cart but out of the order: excluded from totals, the item count and checkout.
    saved_for_later: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))

    cart: Mapped[Cart] = relationship(back_populates="items")
    product: Mapped[Product] = relationship()

    __table_args__ = (
        UniqueConstraint("cart_id", "product_id", name="uq_cart_items_cart_product"),
        CheckConstraint("quantity BETWEEN 1 AND 99", name="quantity_range"),
    )


class Order(TimestampMixin, db.Model):
    """A customer order. Status changes are checked against order_status_transitions by a trigger and logged to
    order_status_history; paid requires a matching succeeded payment."""

    __tablename__ = "orders"

    id: Mapped[int] = mapped_column(primary_key=True)
    # Human-facing reference, generated by PostgreSQL from the id (e.g. FRG-000042).
    order_number: Mapped[str] = mapped_column(
        String(20),
        unique=True,
        nullable=False,
        server_default=text("'FRG-' || lpad(nextval('order_number_seq')::text, 6, '0')"),
    )
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="RESTRICT"), nullable=False, index=True)
    build_id: Mapped[int | None] = mapped_column(ForeignKey("builds.id", ondelete="SET NULL"))
    status: Mapped[OrderStatus] = mapped_column(
        ORDER_STATUS, nullable=False, server_default=OrderStatus.PENDING_PAYMENT.value
    )
    currency: Mapped[str] = mapped_column(CHAR(3), nullable=False)
    subtotal_cents: Mapped[int] = mapped_column(Integer, nullable=False)
    tax_cents: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    shipping_cents: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    total_cents: Mapped[int] = mapped_column(Integer, nullable=False)
    reservation_expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Set when the confirmation email is sent, so a retried task never sends it twice.
    confirmation_sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    items: Mapped[list[OrderItem]] = relationship(back_populates="order", cascade="all, delete-orphan")
    addresses: Mapped[list[OrderAddress]] = relationship(back_populates="order", cascade="all, delete-orphan")
    status_history: Mapped[list[OrderStatusHistory]] = relationship(
        back_populates="order", order_by="OrderStatusHistory.changed_at", viewonly=True
    )
    payments: Mapped[list[Payment]] = relationship(back_populates="order")

    __table_args__ = (
        CheckConstraint("subtotal_cents >= 0 AND tax_cents >= 0 AND shipping_cents >= 0", name="amounts_non_negative"),
        CheckConstraint("total_cents = subtotal_cents + tax_cents + shipping_cents", name="total_consistent"),
        Index("ix_orders_status_created", "status", "created_at"),
        # The reservation sweeper scans only unpaid orders, oldest expiry first.
        Index(
            "ix_orders_pending_reservation_expiry",
            "reservation_expires_at",
            postgresql_where=text("status = 'pending_payment'"),
        ),
    )


class OrderItem(db.Model):
    """Immutable line snapshot: name, SKU and price are copied at purchase time on purpose."""

    __tablename__ = "order_items"

    id: Mapped[int] = mapped_column(primary_key=True)
    order_id: Mapped[int] = mapped_column(ForeignKey("orders.id", ondelete="CASCADE"), nullable=False, index=True)
    product_id: Mapped[int] = mapped_column(ForeignKey("products.id", ondelete="RESTRICT"), nullable=False)
    sku_snapshot: Mapped[str] = mapped_column(String(64), nullable=False)
    name_snapshot: Mapped[str] = mapped_column(String(200), nullable=False)
    unit_price_cents: Mapped[int] = mapped_column(Integer, nullable=False)
    quantity: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    line_total_cents: Mapped[int] = mapped_column(Integer, nullable=False)

    order: Mapped[Order] = relationship(back_populates="items")

    __table_args__ = (
        CheckConstraint("quantity > 0 AND unit_price_cents >= 0", name="positive_values"),
        CheckConstraint("line_total_cents = unit_price_cents * quantity", name="line_total_consistent"),
        UniqueConstraint("order_id", "product_id", name="uq_order_items_order_product"),
    )


class OrderAddress(db.Model):
    """Address snapshot per order, so later edits to a user's address book never rewrite history."""

    __tablename__ = "order_addresses"

    order_id: Mapped[int] = mapped_column(ForeignKey("orders.id", ondelete="CASCADE"), primary_key=True)
    type: Mapped[AddressType] = mapped_column(pg_enum(AddressType, "address_type"), primary_key=True)
    recipient_name: Mapped[str] = mapped_column(String(160), nullable=False)
    phone: Mapped[str | None] = mapped_column(String(32))
    line1: Mapped[str] = mapped_column(String(200), nullable=False)
    line2: Mapped[str | None] = mapped_column(String(200))
    city: Mapped[str] = mapped_column(String(100), nullable=False)
    region: Mapped[str | None] = mapped_column(String(100))
    postal_code: Mapped[str | None] = mapped_column(String(20))
    country_code: Mapped[str] = mapped_column(CHAR(2), nullable=False)

    order: Mapped[Order] = relationship(back_populates="addresses")


class OrderStatusTransition(db.Model):
    """Reference data: the legal edges of the order state machine, enforced by trigger."""

    __tablename__ = "order_status_transitions"

    from_status: Mapped[OrderStatus] = mapped_column(ORDER_STATUS, primary_key=True)
    to_status: Mapped[OrderStatus] = mapped_column(ORDER_STATUS, primary_key=True)

    __table_args__ = (CheckConstraint("from_status <> to_status", name="no_self_loop"),)


class OrderStatusHistory(db.Model):
    """Append-only audit log, written exclusively by trigger."""

    __tablename__ = "order_status_history"

    id: Mapped[int] = mapped_column(primary_key=True)
    order_id: Mapped[int] = mapped_column(ForeignKey("orders.id", ondelete="CASCADE"), nullable=False, index=True)
    from_status: Mapped[OrderStatus | None] = mapped_column(ORDER_STATUS)
    to_status: Mapped[OrderStatus] = mapped_column(ORDER_STATUS, nullable=False)
    changed_by_user_id: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    changed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=text("clock_timestamp()"), nullable=False
    )

    order: Mapped[Order] = relationship(back_populates="status_history")


class StockReservation(db.Model):
    """Phase one of two-phase checkout: stock held for an order until paid or expired."""

    __tablename__ = "stock_reservations"

    id: Mapped[int] = mapped_column(primary_key=True)
    order_id: Mapped[int] = mapped_column(ForeignKey("orders.id", ondelete="CASCADE"), nullable=False)
    product_id: Mapped[int] = mapped_column(ForeignKey("inventory.product_id", ondelete="RESTRICT"), nullable=False)
    quantity: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    status: Mapped[ReservationStatus] = mapped_column(
        pg_enum(ReservationStatus, "reservation_status"),
        nullable=False,
        server_default=ReservationStatus.ACTIVE.value,
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=text("now()"), nullable=False)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        UniqueConstraint("order_id", "product_id", name="uq_stock_reservations_order_product"),
        CheckConstraint("quantity > 0", name="quantity_positive"),
        CheckConstraint("(status = 'active') = (resolved_at IS NULL)", name="resolved_iff_inactive"),
        # Partial index: the expiry sweeper only ever scans active holds.
        Index(
            "ix_stock_reservations_active_expiry",
            "expires_at",
            postgresql_where=text("status = 'active'"),
        ),
    )


class Payment(TimestampMixin, db.Model):
    """A payment attempt with the provider for an order (one per payment intent)."""

    __tablename__ = "payments"

    id: Mapped[int] = mapped_column(primary_key=True)
    order_id: Mapped[int] = mapped_column(ForeignKey("orders.id", ondelete="RESTRICT"), nullable=False, index=True)
    provider: Mapped[str] = mapped_column(String(20), nullable=False, server_default="stripe")
    provider_payment_id: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    amount_cents: Mapped[int] = mapped_column(Integer, nullable=False)
    currency: Mapped[str] = mapped_column(CHAR(3), nullable=False)
    status: Mapped[PaymentStatus] = mapped_column(pg_enum(PaymentStatus, "payment_status"), nullable=False)
    failure_reason: Mapped[str | None] = mapped_column(Text)

    order: Mapped[Order] = relationship(back_populates="payments")

    __table_args__ = (CheckConstraint("amount_cents > 0", name="amount_positive"),)


class ProcessedWebhookEvent(db.Model):
    """Idempotency ledger: a provider event id can be applied at most once."""

    __tablename__ = "processed_webhook_events"

    provider: Mapped[str] = mapped_column(String(20), primary_key=True)
    event_id: Mapped[str] = mapped_column(String(255), primary_key=True)
    event_type: Mapped[str] = mapped_column(String(100), nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    processed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=text("now()"), nullable=False
    )


class PaymentEvent(db.Model):
    """Append-only record of payment outcomes (a trigger forbids updates)."""

    __tablename__ = "payment_events"

    id: Mapped[int] = mapped_column(primary_key=True)
    order_id: Mapped[int] = mapped_column(ForeignKey("orders.id", ondelete="RESTRICT"), nullable=False, index=True)
    payment_id: Mapped[int | None] = mapped_column(ForeignKey("payments.id", ondelete="RESTRICT"))
    kind: Mapped[PaymentEventKind] = mapped_column(pg_enum(PaymentEventKind, "payment_event_kind"), nullable=False)
    details: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, server_default=text("'{}'::jsonb"))
    actor_user_id: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=text("clock_timestamp()"), nullable=False
    )
