"""Initial schema: identity, catalog (joined-table inheritance), builds, commerce.

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 12:32:37.721929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


ENUM_TYPES = (
    "user_role", "address_type", "memory_type", "storage_interface", "storage_form_factor",
    "psu_efficiency", "psu_modularity", "psu_form_factor", "cooler_type", "build_status",
    "order_status", "reservation_status", "payment_status",
)


def upgrade():
    # Case-insensitive text for emails (trusted extension: no superuser needed on PG13+).
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE SEQUENCE IF NOT EXISTS order_number_seq START WITH 1")

    # ### commands auto generated by Alembic, reviewed ###
    op.create_table('board_form_factors',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('width_mm', sa.SmallInteger(), nullable=False),
    sa.Column('depth_mm', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_board_form_factors'))
    )
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('name', name=op.f('uq_brands_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_brands_slug'))
    )
    op.create_table('component_kinds',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('max_per_build', sa.SmallInteger(), nullable=False),
    sa.Column('required_in_build', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('max_per_build >= 1', name=op.f('ck_component_kinds_max_per_build_positive')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_component_kinds')),
    sa.UniqueConstraint('label', name=op.f('uq_component_kinds_label'))
    )
    op.create_table('order_status_transitions',
    sa.Column('from_status', sa.Enum('pending_payment', 'paid', 'fulfilling', 'shipped', 'delivered', 'cancelled', 'refunded', name='order_status'), nullable=False),
    sa.Column('to_status', sa.Enum('pending_payment', 'paid', 'fulfilling', 'shipped', 'delivered', 'cancelled', 'refunded', name='order_status'), nullable=False),
    sa.CheckConstraint('from_status <> to_status', name=op.f('ck_order_status_transitions_no_self_loop')),
    sa.PrimaryKeyConstraint('from_status', 'to_status', name=op.f('pk_order_status_transitions'))
    )
    op.create_table('processed_webhook_events',
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'event_id', name=op.f('pk_processed_webhook_events'))
    )
    op.create_table('sockets',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('vendor', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_sockets'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('customer', 'admin', name='user_role'), server_default='customer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("position('@' in email) > 1", name=op.f('ck_users_email_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('shipping', 'billing', name='address_type'), nullable=False),
    sa.Column('recipient_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('line1', sa.String(length=200), nullable=False),
    sa.Column('line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.CHAR(length=2), server_default='NA', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country_code ~ '^[A-Z]{2}$'", name=op.f('ck_addresses_country_code_iso')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_addresses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index('uq_addresses_one_default_per_type', ['user_id', 'type'], unique=True, postgresql_where=sa.text('is_default'))

    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('draft', 'validated', 'ordered', name='build_status'), server_default='draft', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('share_slug', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT is_public OR share_slug IS NOT NULL', name=op.f('ck_builds_public_requires_slug')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_builds_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_builds')),
    sa.UniqueConstraint('share_slug', name=op.f('uq_builds_share_slug'))
    )
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builds_user_id'), ['user_id'], unique=False)

    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_token', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(user_id, guest_token) = 1', name=op.f('ck_carts_exactly_one_owner')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_carts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts')),
    sa.UniqueConstraint('guest_token', name=op.f('uq_carts_guest_token')),
    sa.UniqueConstraint('user_id', name=op.f('uq_carts_user_id'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('kind_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_categories_not_own_parent')),
    sa.ForeignKeyConstraint(['kind_code'], ['component_kinds.code'], name=op.f('fk_categories_kind_code_component_kinds')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('id', 'kind_code', name='uq_categories_id_kind'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_categories_sibling_name'),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.Uuid(), nullable=True),
    sa.CheckConstraint('expires_at > issued_at', name=op.f('ck_refresh_tokens_expiry_after_issue')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('jti', name=op.f('uq_refresh_tokens_jti'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=20), server_default=sa.text("'FRG-' || lpad(nextval('order_number_seq')::text, 6, '0')"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending_payment', 'paid', 'fulfilling', 'shipped', 'delivered', 'cancelled', 'refunded', name='order_status'), server_default='pending_payment', nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('shipping_cents', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('reservation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('subtotal_cents >= 0 AND tax_cents >= 0 AND shipping_cents >= 0', name=op.f('ck_orders_amounts_non_negative')),
    sa.CheckConstraint('total_cents = subtotal_cents + tax_cents + shipping_cents', name=op.f('ck_orders_total_consistent')),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], name=op.f('fk_orders_build_id_builds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('kind_code', sa.String(length=20), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english'::regconfig, coalesce(name, '')), 'A') || setweight(to_tsvector('english'::regconfig, coalesce(sku, '')), 'B') || setweight(to_tsvector('english'::regconfig, coalesce(description, '')), 'C')", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_cents >= 0', name=op.f('ck_products_price_non_negative')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id', 'kind_code'], ['categories.id', 'categories.kind_code'], name='fk_products_category_kind'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('id', 'kind_code', name='uq_products_id_kind'),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_attributes', ['attributes'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_products_brand_id', ['brand_id'], unique=False)
        batch_op.create_index('ix_products_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_products_kind_active_price', ['kind_code', 'is_active', 'price_cents'], unique=False)
        batch_op.create_index('ix_products_search_vector', ['search_vector'], unique=False, postgresql_using='gin')

    op.create_table('build_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind_code', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_build_items_quantity_positive')),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], name=op.f('fk_build_items_build_id_builds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id', 'kind_code'], ['products.id', 'products.kind_code'], name='fk_build_items_product_kind', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_build_items')),
    sa.UniqueConstraint('build_id', 'product_id', name='uq_build_items_build_product')
    )
    with op.batch_alter_table('build_items', schema=None) as batch_op:
        batch_op.create_index('ix_build_items_build_kind', ['build_id', 'kind_code'], unique=False)

    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity BETWEEN 1 AND 99', name=op.f('ck_cart_items_quantity_range')),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_items_cart_id_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cart_items_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items')),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_items_cart_product')
    )
    op.create_table('case_specs',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind_code', sa.String(length=20), server_default='case', nullable=False),
    sa.Column('max_gpu_length_mm', sa.SmallInteger(), nullable=False),
    sa.Column('max_cooler_height_mm', sa.SmallInteger(), nullable=False),
    sa.Column('max_radiator_mm', sa.SmallInteger(), nullable=True),
    sa.Column('psu_form_factor', sa.Enum('atx', 'sfx', 'sfx_l', name='psu_form_factor'), nullable=False),
    sa.CheckConstraint("kind_code = 'case'", name=op.f('ck_case_specs_kind_matches_table')),
    sa.ForeignKeyConstraint(['product_id', 'kind_code'], ['products.id', 'products.kind_code'], name='fk_case_specs_product_kind', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_case_specs_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_case_specs'))
    )
    op.create_table('cooler_specs',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind_code', sa.String(length=20), server_default='cooler', nullable=False),
    sa.Column('cooler_type', sa.Enum('air', 'aio', name='cooler_type'), nullable=False),
    sa.Column('height_mm', sa.SmallInteger(), nullable=True),
    sa.Column('radiator_mm', sa.SmallInteger(), nullable=True),
    sa.Column('tdp_rating_w', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("(cooler_type = 'air' AND height_mm IS NOT NULL AND radiator_mm IS NULL) OR (cooler_type = 'aio' AND radiator_mm IN (120, 140, 240, 280, 360, 420))", name=op.f('ck_cooler_specs_type_dimensions_consistent')),
    sa.CheckConstraint("kind_code = 'cooler'", name=op.f('ck_cooler_specs_kind_matches_table')),
    sa.ForeignKeyConstraint(['product_id', 'kind_code'], ['products.id', 'products.kind_code'], name='fk_cooler_specs_product_kind', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cooler_specs_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_cooler_specs'))
    )
    op.create_table('cpu_specs',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind_code', sa.String(length=20), server_default='cpu', nullable=False),
    sa.Column('socket_code', sa.String(length=20), nullable=False),
    sa.Column('cores', sa.SmallInteger(), nullable=False),
    sa.Column('threads', sa.SmallInteger(), nullable=False),
    sa.Column('base_clock_mhz', sa.SmallInteger(), nullable=False),
    sa.Column('boost_clock_mhz', sa.SmallInteger(), nullable=False),
    sa.Column('tdp_w', sa.SmallInteger(), nullable=False),
    sa.Column('max_power_w', sa.SmallInteger(), nullable=False),
    sa.Column('has_integrated_graphics', sa.Boolean(), nullable=False),
    sa.CheckConstraint("kind_code = 'cpu'", name=op.f('ck_cpu_specs_kind_matches_table')),
    sa.CheckConstraint('boost_clock_mhz >= base_clock_mhz', name=op.f('ck_cpu_specs_boost_ge_base')),
    sa.CheckConstraint('max_power_w >= tdp_w', name=op.f('ck_cpu_specs_max_power_ge_tdp')),
    sa.CheckConstraint('threads >= cores AND cores > 0', name=op.f('ck_cpu_specs_threads_ge_cores')),
    sa.ForeignKeyConstraint(['product_id', 'kind_code'], ['products.id', 'products.kind_code'], name='fk_cpu_specs_product_kind', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cpu_specs_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['socket_code'], ['sockets.code'], name=op.f('fk_cpu_specs_socket_code_sockets')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_cpu_specs'))
    )
    with op.batch_alter_table('cpu_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cpu_specs_socket_code'), ['socket_code'], unique=False)

    op.create_table('gpu_specs',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind_code', sa.String(length=20), server_default='gpu', nullable=False),
    sa.Column('chipset', sa.String(length=60), nullable=False),
    sa.Column('vram_gb', sa.SmallInteger(), nullable=False),
    sa.Column('length_mm', sa.SmallInteger(), nullable=False),
    sa.Column('slot_width', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('tdp_w', sa.SmallInteger(), nullable=False),
    sa.Column('power_connectors', sa.String(length=60), nullable=False),
    sa.Column('recommended_psu_w', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("kind_code = 'gpu'", name=op.f('ck_gpu_specs_kind_matches_table')),
    sa.CheckConstraint('length_mm > 0 AND tdp_w > 0', name=op.f('ck_gpu_specs_dimensions_positive')),
    sa.ForeignKeyConstraint(['product_id', 'kind_code'], ['products.id', 'products.kind_code'], name='fk_gpu_specs_product_kind', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_gpu_specs_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_gpu_specs'))
    )
    op.create_table('inventory',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name=op.f('ck_inventory_on_hand_non_negative')),
    sa.CheckConstraint('quantity_reserved <= quantity_on_hand', name=op.f('ck_inventory_reserved_le_on_hand')),
    sa.CheckConstraint('quantity_reserved >= 0', name=op.f('ck_inventory_reserved_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_inventory'))
    )
    op.create_table('memory_specs',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind_code', sa.String(length=20), server_default='memory', nullable=False),
    sa.Column('memory_type', sa.Enum('ddr4', 'ddr5', name='memory_type'), nullable=False),
    sa.Column('modules', sa.SmallInteger(), nullable=False),
    sa.Column('module_capacity_gb', sa.SmallInteger(), nullable=False),
    sa.Column('speed_mts', sa.SmallInteger(), nullable=False),
    sa.Column('cas_latency', sa.SmallInteger(), nullable=False),
    sa.Column('height_mm', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('total_capacity_gb', sa.SmallInteger(), sa.Computed('modules * module_capacity_gb', persisted=True), nullable=False),
    sa.CheckConstraint("kind_code = 'memory'", name=op.f('ck_memory_specs_kind_matches_table')),
    sa.CheckConstraint('modules BETWEEN 1 AND 8', name=op.f('ck_memory_specs_modules_range')),
    sa.ForeignKeyConstraint(['product_id', 'kind_code'], ['products.id', 'products.kind_code'], name='fk_memory_specs_product_kind', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_memory_specs_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_memory_specs'))
    )
    with op.batch_alter_table('memory_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_specs_memory_type'), ['memory_type'], unique=False)

    op.create_table('motherboard_specs',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind_code', sa.String(length=20), server_default='motherboard', nullable=False),
    sa.Column('socket_code', sa.String(length=20), nullable=False),
    sa.Column('form_factor_code', sa.String(length=20), nullable=False),
    sa.Column('chipset', sa.String(length=20), nullable=False),
    sa.Column('memory_type', sa.Enum('ddr4', 'ddr5', name='memory_type'), nullable=False),
    sa.Column('memory_slots', sa.SmallInteger(), nullable=False),
    sa.Column('max_memory_gb', sa.SmallInteger(), nullable=False),
    sa.Column('m2_slots', sa.SmallInteger(), nullable=False),
    sa.Column('sata_ports', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("kind_code = 'motherboard'", name=op.f('ck_motherboard_specs_kind_matches_table')),
    sa.CheckConstraint('m2_slots >= 0 AND sata_ports >= 0', name=op.f('ck_motherboard_specs_storage_ports_non_negative')),
    sa.CheckConstraint('memory_slots IN (2, 4, 8)', name=op.f('ck_motherboard_specs_memory_slots_valid')),
    sa.ForeignKeyConstraint(['form_factor_code'], ['board_form_factors.code'], name=op.f('fk_motherboard_specs_form_factor_code_board_form_factors')),
    sa.ForeignKeyConstraint(['product_id', 'kind_code'], ['products.id', 'products.kind_code'], name='fk_motherboard_specs_product_kind', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_motherboard_specs_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['socket_code'], ['sockets.code'], name=op.f('fk_motherboard_specs_socket_code_sockets')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_motherboard_specs'))
    )
    with op.batch_alter_table('motherboard_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motherboard_specs_form_factor_code'), ['form_factor_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_motherboard_specs_memory_type'), ['memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_motherboard_specs_socket_code'), ['socket_code'], unique=False)

    op.create_table('order_addresses',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('shipping', 'billing', name='address_type'), nullable=False),
    sa.Column('recipient_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('line1', sa.String(length=200), nullable=False),
    sa.Column('line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.CHAR(length=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_addresses_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'type', name=op.f('pk_order_addresses'))
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku_snapshot', sa.String(length=64), nullable=False),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('line_total_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint('line_total_cents = unit_price_cents * quantity', name=op.f('ck_order_items_line_total_consistent')),
    sa.CheckConstraint('quantity > 0 AND unit_price_cents >= 0', name=op.f('ck_order_items_positive_values')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_order_items_order_product')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('pending_payment', 'paid', 'fulfilling', 'shipped', 'delivered', 'cancelled', 'refunded', name='order_status'), nullable=True),
    sa.Column('to_status', sa.Enum('pending_payment', 'paid', 'fulfilling', 'shipped', 'delivered', 'cancelled', 'refunded', name='order_status'), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_order_status_history_changed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_history_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_history'))
    )
    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_status_history_order_id'), ['order_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), server_default='stripe', nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.Enum('requires_payment', 'processing', 'succeeded', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name=op.f('ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('provider_payment_id', name=op.f('uq_payments_provider_payment_id'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)

    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('target_price_cents', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_price_cents > 0', name=op.f('ck_price_alerts_target_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_alerts_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_price_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_alerts')),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_price_alerts_user_product')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_history_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'recorded_at', name=op.f('pk_price_history')),
    postgresql_partition_by='RANGE (recorded_at)'
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_price_history_product_recorded', ['product_id', 'recorded_at'], unique=False)

    op.create_table('psu_specs',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind_code', sa.String(length=20), server_default='psu', nullable=False),
    sa.Column('wattage_w', sa.SmallInteger(), nullable=False),
    sa.Column('efficiency', sa.Enum('80plus', '80plus_bronze', '80plus_silver', '80plus_gold', '80plus_platinum', '80plus_titanium', name='psu_efficiency'), nullable=False),
    sa.Column('modularity', sa.Enum('non_modular', 'semi_modular', 'fully_modular', name='psu_modularity'), nullable=False),
    sa.Column('form_factor', sa.Enum('atx', 'sfx', 'sfx_l', name='psu_form_factor'), nullable=False),
    sa.Column('has_12v_2x6', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("kind_code = 'psu'", name=op.f('ck_psu_specs_kind_matches_table')),
    sa.CheckConstraint('wattage_w >= 300', name=op.f('ck_psu_specs_wattage_min')),
    sa.ForeignKeyConstraint(['product_id', 'kind_code'], ['products.id', 'products.kind_code'], name='fk_psu_specs_product_kind', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_psu_specs_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_psu_specs'))
    )
    with op.batch_alter_table('psu_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psu_specs_wattage_w'), ['wattage_w'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_reviews_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('product_id', 'user_id', name='uq_reviews_one_per_user')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_product_id'), ['product_id'], unique=False)

    op.create_table('storage_specs',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind_code', sa.String(length=20), server_default='storage', nullable=False),
    sa.Column('interface', sa.Enum('nvme', 'sata', name='storage_interface'), nullable=False),
    sa.Column('form_factor', sa.Enum('m2_2280', '2.5in', '3.5in', name='storage_form_factor'), nullable=False),
    sa.Column('capacity_gb', sa.Integer(), nullable=False),
    sa.Column('pcie_gen', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("(interface = 'nvme' AND form_factor = 'm2_2280' AND pcie_gen IS NOT NULL) OR (interface = 'sata' AND pcie_gen IS NULL)", name=op.f('ck_storage_specs_interface_consistent')),
    sa.CheckConstraint("kind_code = 'storage'", name=op.f('ck_storage_specs_kind_matches_table')),
    sa.ForeignKeyConstraint(['product_id', 'kind_code'], ['products.id', 'products.kind_code'], name='fk_storage_specs_product_kind', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_storage_specs_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_storage_specs'))
    )
    op.create_table('case_supported_form_factors',
    sa.Column('case_product_id', sa.Integer(), nullable=False),
    sa.Column('form_factor_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['case_product_id'], ['case_specs.product_id'], name=op.f('fk_case_supported_form_factors_case_product_id_case_specs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_factor_code'], ['board_form_factors.code'], name=op.f('fk_case_supported_form_factors_form_factor_code_board_form_factors')),
    sa.PrimaryKeyConstraint('case_product_id', 'form_factor_code', name=op.f('pk_case_supported_form_factors'))
    )
    op.create_table('cooler_supported_sockets',
    sa.Column('cooler_product_id', sa.Integer(), nullable=False),
    sa.Column('socket_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cooler_product_id'], ['cooler_specs.product_id'], name=op.f('fk_cooler_supported_sockets_cooler_product_id_cooler_specs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['socket_code'], ['sockets.code'], name=op.f('fk_cooler_supported_sockets_socket_code_sockets')),
    sa.PrimaryKeyConstraint('cooler_product_id', 'socket_code', name=op.f('pk_cooler_supported_sockets'))
    )
    op.create_table('stock_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('active', 'committed', 'released', 'expired', name='reservation_status'), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'active') = (resolved_at IS NULL)", name=op.f('ck_stock_reservations_resolved_iff_inactive')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_stock_reservations_quantity_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_stock_reservations_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.product_id'], name=op.f('fk_stock_reservations_product_id_inventory'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_reservations')),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_stock_reservations_order_product')
    )
    with op.batch_alter_table('stock_reservations', schema=None) as batch_op:
        batch_op.create_index('ix_stock_reservations_active_expiry', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'active'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_reservations', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_reservations_active_expiry', postgresql_where=sa.text("status = 'active'"))

    op.drop_table('stock_reservations')
    op.drop_table('cooler_supported_sockets')
    op.drop_table('case_supported_form_factors')
    op.drop_table('storage_specs')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_product_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('psu_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psu_specs_wattage_w'))

    op.drop_table('psu_specs')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_product_recorded')

    op.drop_table('price_history')
    op.drop_table('price_alerts')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))

    op.drop_table('payments')
    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status_history_order_id'))

    op.drop_table('order_status_history')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    op.drop_table('order_addresses')
    with op.batch_alter_table('motherboard_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motherboard_specs_socket_code'))
        batch_op.drop_index(batch_op.f('ix_motherboard_specs_memory_type'))
        batch_op.drop_index(batch_op.f('ix_motherboard_specs_form_factor_code'))

    op.drop_table('motherboard_specs')
    with op.batch_alter_table('memory_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_specs_memory_type'))

    op.drop_table('memory_specs')
    op.drop_table('inventory')
    op.drop_table('gpu_specs')
    with op.batch_alter_table('cpu_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cpu_specs_socket_code'))

    op.drop_table('cpu_specs')
    op.drop_table('cooler_specs')
    op.drop_table('case_specs')
    op.drop_table('cart_items')
    with op.batch_alter_table('build_items', schema=None) as batch_op:
        batch_op.drop_index('ix_build_items_build_kind')

    op.drop_table('build_items')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_search_vector', postgresql_using='gin')
        batch_op.drop_index('ix_products_kind_active_price')
        batch_op.drop_index('ix_products_category_id')
        batch_op.drop_index('ix_products_brand_id')
        batch_op.drop_index('ix_products_attributes', postgresql_using='gin')

    op.drop_table('products')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index('ix_orders_status_created')

    op.drop_table('orders')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    op.drop_table('categories')
    op.drop_table('carts')
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builds_user_id'))

    op.drop_table('builds')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index('uq_addresses_one_default_per_type', postgresql_where=sa.text('is_default'))

    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('sockets')
    op.drop_table('processed_webhook_events')
    op.drop_table('order_status_transitions')
    op.drop_table('component_kinds')
    op.drop_table('brands')
    op.drop_table('board_form_factors')
    # ### end Alembic commands ###

    op.execute("DROP SEQUENCE IF EXISTS order_number_seq")
    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
